### ISSUE TITLE
Bot skips to next track mid song

### ISSUE THREAD

**Issue by gfrewqpoiu** [Budovi/ddmbot#11] opened 2017-05-26 18:28 UTC
The bot currently always gets a `[tls@xxxxx] ERROR in the Pull function` during some part of playing a song which then either spawns a FFMPEG `Input buffer exhausted before End element is found` error or a `WebM read error` which is followed by another tls error with the text `The session has been invalidated for some reason`
I am using:
Python 3.6.1
Ddmbot with new peewee patch applied
peewee 2.10.1
YouTube-dl 2017.05.23
ffmpeg 3.3.1 with libfdk_aac support
on Arch Linux with the 4.9.15 Kernel and 1 GB of ram

**Comment by Budovi** [comment] 2017-05-28 08:58
This is clearly a bug caused by an external dependency, so the best shot is to confirm and find a viable workaround.
- [x] Check what TLS library `aur/ffmpeg-libfdk_aac` is using (probably GnuTLS)
- [x] Check whether `aur/ffmpeg-libfdk_aac` can be successfully built with a different library
- [ ] Confirm the bug is present by using a download tool with the same backend TLS library
- [x] Check whether the secure connection is enforced by the service (I guess it's mostly YouTube)

If possible (due to time restrictions):
- [ ] Debug the connection between ffmpeg and target service
- [ ] Fill up upstream bug report

**Comment by Budovi** [comment] 2017-06-02 08:12
@gfrewqpoiu how reliably can you reproduce the error? It happened only once in my testing in a really long time, so if you have any tips on how to increase the chances that would be helpful.

In any case, I was able to successfully build `aur/ffmpeg-libfdk_aac` with `openssl` as a TLS backend instead of `gnutls`. You can try it yourself if you want -- [PKGBUILD](https://www.dropbox.com/s/cce4sge8lruy6dn/PKGBUILD?dl=1).

**Comment by Budovi** [comment] 2017-06-04 13:47
So the progress so far:
* ffmpeg is using GnuTLS as a backend, both in official manjaro repositories and AUR
* ffmpeg can be build with OpenSSL library instead, but the problem still occurs
* HTTPS is indeed enforced by YouTube, so even if the TLS was indeed a cause, there is no simple workaround

By the looks of it, the problem is below the TLS layer because both libraries are complaining about unexpected end of the input. It is unclear why there is a difference in the occurrence among different locations.

Now I think the further progress should be as follows:
- [ ] Confirm the bug is only present when "downloading" the audio through ffmpeg
    - This probably involves checking the rate ffmpeg is downloading the file and simulating that
- [ ] Figure out the way to intercept the communication and investigate it

**Comment by Budovi** [comment] 2017-07-07 11:37
Since the issue seems to have sorted out itself, closing for now.

**Comment by Budovi** [comment] 2017-07-08 10:45
Ok so the problem is still present,
on the other hand I think I found an easy fix... ffmpeg has an option to reconnect and it seems like the link is still valid.

**Comment by Budovi** [comment] 2017-07-08 10:53
Let me know if there are any drawbacks or further issues with this fix.

**Closed as completed by Budovi** 2017-07-08 10:53 UTC
Labels: bug
